### ISSUE TITLE
[FEATURE REQUEST] Updates available-notification: Open Software Update section upon clicking (and present options directly in the notification)

### ISSUE THREAD

**Issue by RavenMacDaddy** [marticliment/WingetUI#680]
# TODO:
 - [ ] Add better notifications
 - [ ] (#692).

## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

At least I didn't see an entry for this… When WingetUI notifies the user that updates are available, it would be intuitive if clicking that notification would open the app - with the Software Update section active.

Also, if possible, present options to either update those apps by clicking a button in that same notification, or to dismiss it, where the latter would postpone the notification till the next (user selected) update cycle, e.g., 2 or 4 hours.

![image](https://user-images.githubusercontent.com/67732686/215852453-65bbae00-0991-4f6b-90ca-c8487d9c8705.png)

**Comment by marticliment** [comment]
Note for myself: check `zroya` (https://github.com/malja/zroya/)

**Comment by ppvnf** [comment]
jfyi https://github.com/marticliment/WingetUI/issues/646 seems related

**Comment by marticliment** [comment]
Yes, that are indeed related, though this could be more related to the default WingetUI tab when opened
