### ISSUE TITLE
[CHOCO] Improve info menu

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#834]
Besides the consideration I made in https://github.com/marticliment/WingetUI/issues/484#issuecomment-1480425356 regarding release notes, some changes can be made in order to improve Chocolatey info menu:

<img width="269" alt="Screenshot 2023-03-23 082509" src="https://user-images.githubusercontent.com/73800734/227132468-017b0c20-bfa0-410e-9051-c69f470d016f.png">

Regarding https://community.chocolatey.org/packages/Firefox: 

- [x] Publisher should be Software Author(s) https://github.com/marticliment/WingetUI/issues/834#issuecomment-1510419919
- [ ] Package Maintainer(s) should be the Publisher (it can be more than one like in https://community.chocolatey.org/packages/adobereader) 
- [x] License should only display the link (unavailable should be hidden if a link is found)

Also: 
<img width="485" alt="Screenshot 2023-03-23 083055" src="https://user-images.githubusercontent.com/73800734/227133746-5c23fb8c-d4c5-4574-a890-3c593850a521.png">

- [x] Installer url and installer type are missing (is there really no way to get them? if they really cannot be found you could hide these fields https://github.com/marticliment/WingetUI/issues/834#issuecomment-1516653724)
- [x] Installer sha256 should be hidden and instead a new field called sha512 should appear. Parsing should be improved to remove ' '
- [ ]  Replace release notes with regular notes https://github.com/marticliment/WingetUI/issues/834#issuecomment-1517012717

**Comment by marticliment** [comment]
The unchecked information can not be loaded from choco-cli

**Comment by ppvnf** [comment]
> The unchecked information can not be loaded from choco-cli

Would be possible to get it from the nuspec file?
<img width="853" alt="Screenshot 2023-04-16 163157" src="https://user-images.githubusercontent.com/73800734/232320092-bc1183fb-9898-40cf-aeb9-d9e2fc3c1e89.png">
https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/firefox/firefox.nuspec

**Comment by marticliment** [comment]
We could only get the autor, the installer url is only available on the chocolateyInstall.ps1 file, but that file varies on every package

**Comment by ppvnf** [comment]
> And also, the package source is only available on certain packages

So, this method is not reliable?
From my understanding:
`<authors> </authors>` = Author
`<owners> </owners>` = Publisher

> We could only get the autor, the installer url is only available on the chocolateyInstall.ps1 file, but that file varies on every package

I read somewhere that you would need to use nuget and it is not so straightforward to get the installer url

**Comment by ppvnf** [comment]
> I read somewhere that you would need to use nuget and it is not so straightforward to get the installer url

I don't know if you could use the same api as chocolatey website, because I think they already have a nupkg "reader" since there is an option to download it for every package

**Comment by marticliment** [comment]
I will google it, it looks promising

**Comment by ppvnf** [comment]
another thing, I don't think release notes are a thing in Chocolatey (although I am not totally sure). How about replacing it with regular notes or hiding it?

<img width="854" alt="Screenshot 2023-04-21 000827" src="https://user-images.githubusercontent.com/73800734/233498901-f76b006e-f438-4c03-ba19-a271721e926e.png">
<img width="506" alt="Screenshot 2023-04-21 000852" src="https://user-images.githubusercontent.com/73800734/233498904-57f6dd74-29cd-4dac-981c-705d310fae63.png">

**Comment by marticliment** [comment]
All the fixable issues from here have been fixed
